name: CI Pipeline Sistema Ventas

on:
  push:
    branches: ["main", "productos-crud"]
  pull_request:
    branches: ["main", "productos-crud"]

jobs:
  backend_lint:
    name: Backend Lint (Pint)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, intl, pdo_pgsql, bcmath

      - uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - run: composer install --prefer-dist --no-interaction

      - run: ./vendor/bin/pint --test


  backend_static_analysis:
    name: Backend Static Analysis (PHPStan)
    runs-on: ubuntu-latest
    needs: backend_lint
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, intl, pdo_pgsql, bcmath

      - uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - run: composer install --prefer-dist --no-interaction

      - run: ./vendor/bin/phpstan analyse


  backend_tests:
    name: Backend Tests (PostgreSQL)
    runs-on: ubuntu-latest
    needs: backend_static_analysis

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: compras_ventas
          POSTGRES_USER: compras_user
          POSTGRES_PASSWORD: compras_pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U compras_user -d compras_ventas"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, intl, pdo_pgsql, bcmath

      - uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - run: composer install --prefer-dist --no-interaction

      - run: |
          cp .env.example .env
          php artisan key:generate

      - run: php artisan migrate --force
        env:
          DB_CONNECTION: pgsql
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
          DB_DATABASE: compras_ventas
          DB_USERNAME: compras_user
          DB_PASSWORD: compras_pass

      - run: php artisan test
        env:
          DB_CONNECTION: pgsql
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
          DB_DATABASE: compras_ventas
          DB_USERNAME: compras_user
          DB_PASSWORD: compras_pass


  frontend_lint:
    name: Frontend Lint
    runs-on: ubuntu-latest
    needs: backend_tests
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - uses: actions/cache@v4
        with:
          path: node_modules
          key: npm-${{ hashFiles('package-lock.json') }}

      - run: npm ci
      - run: npm run lint


  frontend_tests:
    name: Frontend Tests
    runs-on: ubuntu-latest
    needs: frontend_lint
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - uses: actions/cache@v4
        with:
          path: node_modules
          key: npm-${{ hashFiles('package-lock.json') }}

      - run: npm ci

      - run: npm run test --if-present
        env:
          LARAVEL_BYPASS_ENV_CHECK: 1
          CI: true



  frontend_build:
    name: Frontend Build
    runs-on: ubuntu-latest
    needs: frontend_tests
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - uses: actions/cache@v4
        with:
          path: node_modules
          key: npm-${{ hashFiles('package-lock.json') }}

      - run: npm ci
      - run: npm run build
