name: CD Production

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - "CI Pipeline Sistema Ventas"
      - "Quality Gates"
      #- "CD Staging"
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Build artifact
        run: |
          tar -czf app.tar.gz \
            --warning=no-file-changed \
            --ignore-failed-read \
            --exclude=.git \
            --exclude=node_modules \
             --exclude=storage/logs \
            .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: app.tar.gz

  deploy:
    needs: build
    runs-on: self-hosted
    environment: producction

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app-build

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PROD_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.PROD_SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Production
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          RELEASE_DIR=${{ secrets.PROD_APP_PATH }}/releases/$TIMESTAMP

           ssh ${{ secrets.PROD_SSH_USER }}@${{ secrets.PROD_SSH_HOST }} "
            echo \"$(date '+%Y-%m-%d %H:%M:%S') Deploying release $TIMESTAMP\" >> ${{ secrets.PROD_APP_PATH }}/logs/deploy.log
            mkdir -p $RELEASE_DIR
          "

          rsync -avz app.tar.gz ${{ secrets.PROD_SSH_USER }}@${{ secrets.PROD_SSH_HOST }}:$RELEASE_DIR

          ssh ${{ secrets.PROD_SSH_USER }}@${{ secrets.PROD_SSH_HOST }} "
            cd $RELEASE_DIR &&
            tar -xzf app.tar.gz &&
            rm app.tar.gz &&

            # Symlink .env compartido
            ln -sfn ${{ secrets.PROD_APP_PATH }}/shared/.env .env &&

            # Symlink SQLite compartido
            mkdir -p database &&
            ln -sfn ${{ secrets.PROD_APP_PATH }}/shared/database/database.sqlite database/database.sqlite &&

            php artisan migrate --force &&

            php artisan optimize:clear &&

            # matar servidor anterior
            pkill -f \"artisan serve\" || true &&

            # levantar servidor
            nohup php artisan serve --host=0.0.0.0 --port=8000 > /tmp/laravel-prod.log 2>&1 &

            # cambio atÃ³mico del symlink current
            ln -sfn $RELEASE_DIR ${{ secrets.PROD_APP_PATH }}/current
          "

      - name: Health check
        run: |
          sleep 5
          curl -f ${{ secrets.PROD_HEALTH_URL }}

      - name: Rollback on failure
        # if: failure()
        run: |
          ssh ${{ secrets.PROD_SSH_USER }}@${{ secrets.PROD_SSH_HOST }} "
            cd ${{ secrets.PROD_APP_PATH }}/releases
            PREV=\$(ls -t | sed -n '2p')
            if [ -n \"\$PREV\" ]; then
              ln -sfn ${{ secrets.PROD_APP_PATH }}/releases/\$PREV ${{ secrets.PROD_APP_PATH }}/current
              echo \"Rollback to \$PREV\" >> ${{ secrets.PROD_APP_PATH }}/deploy.log
            else
              echo \"No previous release to rollback\" >> ${{ secrets.PROD_APP_PATH }}/deploy.log
            fi
          "

